Django_project/quotes/quoteapp/urls.py
from django.urls import path
from . import views

app_name = 'quoteapp'

urlpatterns = [
    path('', views.main, name='main'),
    path('quote/', views.quote, name='quote'),
    path('tag/', views.tag, name='tag'),
    path('author/', views.author, name='author'),
    path('detail/<int:quote_id>', views.detail, name='detail'),
    path('delete/<int:quote_id>', views.delete_quote, name='delete'),
    path('scrape-and-add/', views.scrape_and_add, name='scrape_and_add'),
    path('author/<int:author_id>/', views.author_detail, name='author_detail'),
]

Django_project/quotes/quotes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('quoteapp.urls')),
    path('users/', include('users.urls')),
]

Django_project/quotes/users/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

Django_project/quotes/quoteapp/models.py
from django.db import models

# Create your models here.
class Author(models.Model):
    fullname = models.CharField(max_length=150, null=False, unique=True)
    born_date = models.DateField(null=True)
    born_location = models.CharField(max_length=150)
    description = models.TextField()

    def __str__(self):
        return f"{self.fullname}"

class Tag(models.Model):
    tag_name = models.CharField(max_length=150, null=False, unique=True)

    def __str__(self):
        return f"{self.tag_name}"

class Quote(models.Model):
    artist = models.ForeignKey(Author, on_delete=models.CASCADE)
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return f"{self.quote}"

Django_project/quotes/quoteapp/forms.py
from django.forms import ModelForm, CharField, TextInput, ModelChoiceField, ModelMultipleChoiceField, SelectMultiple
from .models import Tag, Quote, Author


class AuthorForm(ModelForm):
    fullname = CharField(min_length=5, max_length=50, required=True, widget=TextInput())
    born_date = CharField(min_length=5, max_length=50, required=True, widget=TextInput())
    born_location = CharField(min_length=5, max_length=50, required=True, widget=TextInput())
    description = CharField(min_length=5, max_length=50, required=True, widget=TextInput())

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']

class TagForm(ModelForm):
    tag_name = CharField(min_length=3, max_length=25, required=True, widget=TextInput())

    class Meta:
        model = Tag
        fields = ['tag_name']

class QuoteForm(ModelForm):
    artist = ModelChoiceField(queryset=Author.objects.all())
    quote = CharField(min_length=5, max_length=50, required=True, widget=TextInput())
    tags = ModelMultipleChoiceField(queryset=Tag.objects.all(), widget=SelectMultiple, required=False)

    class Meta:
        model = Quote
        fields = ['artist', 'quote', 'tags']

Django_project/quotes/quoteapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

from .forms import TagForm, QuoteForm, AuthorForm
from .models import Tag, Quote, Author
from .management.commands import scrape_quotes


# Create your views here.
def main(request):
    quotes = Quote.objects.all()
    return render(request, 'quoteapp/index.html', {"quotes": quotes})

@login_required
def delete_quote(request, quote_id):
    Quote.objects.get(pk=quote_id).delete()
    return redirect(to='quoteapp:main')

def author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quoteapp:main')
        else:
            return render(request, 'quoteapp/author.html', {'form': form})

    return render(request, 'quoteapp/author.html', {'form': AuthorForm()})

def tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quoteapp:main')
        else:
            return render(request, 'quoteapp/tag.html', {'form': form})

    return render(request, 'quoteapp/tag.html', {'form': TagForm()})

def quote(request):
    tags = Tag.objects.all()

    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save()

            choice_tags = Tag.objects.filter(tag_name__in=request.POST.getlist('tags'))
            for tag in choice_tags.iterator():
                new_quote.tags.add(tag)

            return redirect(to='quoteapp:main')
        else:
            return render(request, 'quoteapp/quote.html', {"tags": tags, 'form': form})

    return render(request, 'quoteapp/quote.html', {"tags": tags, 'form': QuoteForm()})

def detail(request, quote_id):
    quote = get_object_or_404(Quote, pk=quote_id)
    return render(request, 'quoteapp/detail.html', {"quote": quote})

def author_detail(request, author_id):
    author = get_object_or_404(Author, pk=author_id)
    return render(request, 'quoteapp/author_detail.html', {'author': author})

def scrape_and_add(request):
    # Функція для виклику скрапінгу та додавання даних у базу
    scrape_quotes.main()
    return redirect(to='quoteapp:main')

Django_project/quotes/quoteapp/templates/quoteapp/author.html
{% extends "quoteapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quoteapp:author' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Authors fullname:
            {{ form.fullname }}
        </label>
        <span>{{ form.errors.fullname }}</span>
    </div>
    <div style="padding: 10px">
        <label> Authors born date:
            {{ form.born_date }}
        </label>
        <span>{{ form.errors.born_date }}</span>
    </div>
    <div style="padding: 10px">
        <label> Authors born location:
            {{ form.born_location }}
        </label>
        <span>{{ form.errors.born_location }}</span>
    </div>
    <div style="padding: 10px">
        <label> Description:
            {{ form.description }}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

Django_project/quotes/quoteapp/templates/quoteapp/author_detail.html
{% extends "quoteapp/base.html" %}

{% block content %}
    <h1>Author Detail</h1>
    <p><strong>Full Name:</strong> {{ author.fullname }}</p>
    <p><strong>Born Date:</strong> {{ author.born_date }}</p>
    <p><strong>Born Location:</strong> {{ author.born_location }}</p>
    <p><strong>Description:</strong> {{ author.description }}</p>
{% endblock %}

Django_project/quotes/quoteapp/templates/quoteapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Quote information</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
    {% load static %}
    <link rel="stylesheet" href="{% static 'quoteapp/style.css' %}">
</head>
<body>
<main class="container">
    <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
        <ul>
            <li><a href="/" role="button"> Go back to the main page </a></li>
        </ul>
    </nav>
    {% block content %} {% endblock %}
</main>
</body>
</html>

Django_project/quotes/quoteapp/templates/quoteapp/detail.html
{% extends "quoteapp/base.html" %} {% load extract_tags %} {% block content %}

<h1>{{quote.quote}}</h1>
<p>Author: <b>{{quote.artist}}</b></p>

<p>Tags: <small> {{ quote.tags|tags }} </small></p>
{% endblock %}

Django_project/quotes/quoteapp/templates/quoteapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Perfect quotes</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
</head>
<body>
<main class="container">
    <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
        {% if user.is_authenticated %}
        <ul>
            <li><a href="{% url 'quoteapp:author' %}" role="button">Add author</a></li>
            <li><a href="{% url 'quoteapp:tag' %}" role="button">Add tag</a></li>
            <li><a href="{% url 'quoteapp:quote' %}" role="button">Add quote</a></li>
        </ul>
        <ul>
            <li>Welcome <b>{{ user.username }}!</b></li>
            <li><a href="{% url 'users:logout' %}" role="button">Logout</a></li>
        </ul>
        {% else %}
        <ul>
            <li><a href="{% url 'users:signup' %}" role="button">Sign Up</a></li>
            <li><a href="{% url 'users:login' %}" role="button">Login</a></li>
        </ul>
        {% endif %}
    </nav>

    <div>
        <form action="{% url 'quoteapp:scrape_and_add' %}" method="post">
            {% csrf_token %}
            <button type="submit">Download all articles</button>
        </form>
    </div>

    <div style="text-align: center;">
        {% for quote in quotes %}
        <ul>
            <a href="{% url 'quoteapp:author_detail' quote.artist.id %}" role="button">{{ quote.artist.fullname }}</a>
            <a href="{% url 'quoteapp:detail' quote.id %}" role="button" class="outline"> {{ quote.quote|truncatechars:95 }} </a>
            {% if user.is_authenticated %}
            <a href="{% url 'quoteapp:delete' quote.id %}" role="button" class="contrast"> Delete quote </a>
            {% endif %}
        </ul>
        {% endfor %}
    </div>

</main>
</body>
</html>

Django_project/quotes/quoteapp/templates/quoteapp/quote.html
{% extends "quoteapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quoteapp:quote' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Enter quote:
            {{ form.quote }}
        </label>
        <span>{{ form.errors.quote }}</span>
    </div>
    <div style="padding: 10px">
         <label>Select author:
            {{ form.artist }}
        </label>
        <span>{{ form.errors.artist }}</span>
    </div>
    <div style="padding: 10px">
        <label>Select tags:</label>
            {{ form.tags }}
        <span class="error">{{ form.errors.tags }}</span>
    </div>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

Django_project/quotes/quoteapp/templates/quoteapp/tag.html
{% extends "quoteapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quoteapp:tag' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the tag name:
            {{form.tag_name}}
        </label>
        <span>{{ form.errors.tag_name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}